http:
    port: ${PORT}
admin:
    port: ${ADMIN_PORT}
    host: ${ADMIN_HOST}
apiEndpoints:
    api:
        host: ${API_HOST}
        paths: "/ip"
    consumer:
        host: ${CONSUMER_HOST}
        paths: "/api/v1/consumer/*"
    document:
        host: ${DOCUMENT_HOST}
        paths: "/api/v1/document/*"

serviceEndpoints:
    httpbin:
        url: ${HTTPBIN_URL}
    consumerService:
        url: ${CONSUMER_SERVICE_URL}
    documentService:
        url: ${DOCUMENT_SERVICE_URL}
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    default:
        apiEndpoints:
            - api
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            - key-auth:
                  - proxy:
                        - action:
                              serviceEndpoint: httpbin
                              changeOrigin: true

    consumerPipeline:
        apiEndpoints:
            - consumer
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            #- key-auth:
            - proxy:
                  - action:
                        serviceEndpoint: consumerService
                        changeOrigin: true

    documentPipeline:
        apiEndpoints:
            - document
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            #- key-auth:
            - proxy:
                  - action:
                        serviceEndpoint: documentService
                        changeOrigin: true
