http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    api:
        host: localhost
        paths: "/ip"
    consumer:
        host: ${CONSUMER_HOST:-localhost}
        path: "/api/v1/consumer/*"
    document:
        host: ${DOCUMENT_HOST}
        path: "/api/v1/document/*"
serviceEndpoints:
    httpbin:
        url: "https://httpbin.org"
    consumerService:
        url: ${CONSUMER_SERVICE_URL:-http://localhost:8000}
    documentService:
        url: ${DOCUMENT_SERVICE_URL:-http://localhost:6000}
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    default:
        apiEndpoints:
            - api
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            # - key-auth:
            - proxy:
                  - action:
                        serviceEndpoint: httpbin
                        changeOrigin: true

    consumerPipeline:
        apiEndpoints:
            - consumer
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            # - key-auth:
            - proxy:
                  - action:
                        serviceEndpoint: consumerService
                        changeOrigin: true

    documentPipeline:
        apiEndpoints:
            - document
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            # - key-auth:
            - proxy:
                  - action:
                        serviceEndpoint: documentService
                        changeOrigin: true
