http:
    port: 8080
    cors:
        origin:
            - "*"
            - ${CORS}
        methods: "GET, POST, PUT, DELETE"
        credentials: true

apiEndpoints:
    consumer:
        host: "*"
        path: "/api/v1/consumer/*"
    document:
        host: "*"
        path: "/api/v1/document/*"

serviceEndpoints:
    consumerService:
        url: ${CONSUMER_SERVICE_URL}
    documentService:
        url: ${DOCUMENT_SERVICE_URL}

policies:
    - basic-auth
    - cors
    - log
    - expression
    - key-auth
    - oauth2
    - proxy
    - rate-limit

pipelines:
    consumerPipeline:
        apiEndpoints:
            - consumer
        policies:
            - cors:
                  - action:
                        origin:
                            - ${CORS}
                            - "*"
                        methods: "GET, POST, PUT, DELETE"
                        credentials: true
            - log:
                  - action:
                        message: "consumer received"
                        level: "info"
            - proxy:
                  - action:
                        serviceEndpoint: consumerService
                        changeOrigin: true

    documentPipeline:
        apiEndpoints:
            - document
        policies:
            - cors:
                  - action:
                        origin:
                            - ${CORS}
                            - "*"
                        methods: "GET, POST, PUT, DELETE"
                        credentials: true
            - log:
                  - action:
                        message: "document received"
                        level: "info"
            - proxy:
                  - action:
                        serviceEndpoint: documentService
                        changeOrigin: true
