http:
    port: 8080
    cors:
        origin: "*"
        methods: "GET, POST, PUT, DELETE"

apiEndpoints:
    api:
        host: localhost
        paths: "/ip"
    consumer:
        host: "*"
        path: "/api/v1/consumer/*"
    document:
        host: "*"
        path: "/api/v1/document/*"
serviceEndpoints:
    httpbin:
        url: "https://httpbin.org"
    consumerService:
        url: ${CONSUMER_SERVICE_URL}
    documentService:
        url: ${DOCUMENT_SERVICE_URL}
policies:
    - basic-auth
    - cors
    - log
    - expression
    - key-auth
    - oauth2
    - proxy
    - rate-limit
pipelines:
    default:
        apiEndpoints:
            - api
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            # - key-auth:
            - proxy:
                  - action:
                        serviceEndpoint: httpbin
                        changeOrigin: true

    consumerPipeline:
        apiEndpoints:
            - consumer
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            # - key-auth:
            - cors:
                  - action:
                        origin: "*"
                        methods:
                            - GET
                            - POST
                            - PUT
                            - PATCH
                            - DELETE
            - log:
                  - action:
                        message: "consumer received"
                        level: "info"
            - proxy:
                  - action:
                        serviceEndpoint: consumerService
                        changeOrigin: true

    documentPipeline:
        apiEndpoints:
            - document
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            # - key-auth:
            - cors:
                  action:
                      origin:
                          - "*"
                      methods:
                          - GET
                          - POST
                          - PUT
                          - PATCH
                          - DELETE
            - log:
                  - action:
                        message: "document received"
                        level: "info"
            - proxy:
                  - action:
                        serviceEndpoint: documentService
                        changeOrigin: true
